-- 1. Update CLOB_NULLABLE to Non-Null (ID 2 was NULL)
UPDATE DEMO.CLOB_TEST SET CLOB_NULLABLE = 'Updated to a value' WHERE ID = 2;

-- 2. Update CLOB_NULLABLE to NULL (ID 1 was Non-Null)
UPDATE DEMO.CLOB_TEST SET CLOB_NULLABLE = NULL WHERE ID = 1;

-- 3. Update CLOB_REQUIRED to Non-Null (ID 1 was EMPTY)
UPDATE DEMO.CLOB_TEST SET CLOB_REQUIRED = 'Updated Required' WHERE ID = 1;

-- 4. Update CLOB_REQUIRED to EMPTY_CLOB (ID 2 was Non-Null)
UPDATE DEMO.CLOB_TEST SET CLOB_REQUIRED = EMPTY_CLOB() WHERE ID = 2;

-- 5. Update non-CLOB column
UPDATE DEMO.CLOB_TEST SET DESCRIPTION = 'Updated Description' WHERE ID = 3;

COMMIT;
