-- Create a sample table
CREATE TABLE DEMO.EMPLOYEES (
    EMPLOYEE_ID NUMBER(6) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    EMAIL VARCHAR2(100),
    HIRE_DATE DATE,
    SALARY NUMBER(8,2),
    DEPARTMENT VARCHAR2(50)
);

-- Grant necessary permissions if needed (though user likely has them)
-- GRANT SELECT ON DEMO.EMPLOYEES TO DEMO;

-- Table for Use Case 2: No Primary Key
CREATE TABLE DEMO.DEPARTMENTS (
    DEPT_ID NUMBER NOT NULL,
    DEPT_NAME VARCHAR2(50),
    LOCATION_ID NUMBER
);

CREATE UNIQUE INDEX DEMO.DEPT_ID_IDX ON DEMO.DEPARTMENTS (DEPT_ID);

-- Table for Use Case 3: No Primary Key with Delete Support (SMT workaround)
CREATE TABLE DEMO.JOBS (
    JOB_ID VARCHAR2(10) NOT NULL,
    JOB_TITLE VARCHAR2(35),
    MIN_SALARY NUMBER(6),
    MAX_SALARY NUMBER(6)
);

-- Table for Use Case 4: Referential Integrity (Parent)
CREATE TABLE DEMO.CUSTOMERS (
    CUSTOMER_ID NUMBER(10) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100)
);

-- Table for Use Case 4: Referential Integrity (Child)
CREATE TABLE DEMO.ORDERS (
    ORDER_ID NUMBER(10) PRIMARY KEY,
    ORDER_DATE DATE DEFAULT SYSDATE,
    CUSTOMER_ID NUMBER(10),
    TOTAL_AMOUNT NUMBER(10, 2),
    CONSTRAINT FK_ORDERS_CUSTOMERS
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DEMO.CUSTOMERS(CUSTOMER_ID)
        DEFERRABLE INITIALLY DEFERRED
);
