WHENEVER SQLERROR EXIT SQL.SQLCODE;
-- Drop existing tables for idempotency
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DEMO.ORDERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DEMO.CUSTOMERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DEMO.EMPLOYEES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DEMO.DEPARTMENTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DEMO.JOBS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DEMO.DATA_TYPES_TEST CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW DEMO.DATA_TYPES_MV';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -12003 THEN RAISE; END IF;
END;
/

-- Create a sample table
CREATE TABLE DEMO.EMPLOYEES (
    EMPLOYEE_ID NUMBER(6) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    EMAIL VARCHAR2(100),
    HIRE_DATE DATE,
    SALARY NUMBER(8,2),
    DEPARTMENT VARCHAR2(50)
);

-- Grant necessary permissions if needed (though user likely has them)
-- GRANT SELECT ON DEMO.EMPLOYEES TO DEMO;

-- Table for Use Case 2: No Primary Key
CREATE TABLE DEMO.DEPARTMENTS (
    DEPT_ID NUMBER(10) NOT NULL,
    DEPT_NAME VARCHAR2(50),
    LOCATION_ID NUMBER(4)
);

CREATE UNIQUE INDEX DEMO.DEPT_ID_IDX ON DEMO.DEPARTMENTS (DEPT_ID);
CREATE INDEX DEMO.DEPT_NAME_IDX ON DEMO.DEPARTMENTS (DEPT_NAME);
CREATE INDEX DEMO.LOCATION_ID_IDX ON DEMO.DEPARTMENTS (LOCATION_ID);

-- Table for Use Case 3: No Primary Key with Delete Support (SMT workaround)
CREATE TABLE DEMO.JOBS (
    JOB_ID VARCHAR2(10) NOT NULL,
    JOB_TITLE VARCHAR2(35),
    MIN_SALARY NUMBER(6),
    MAX_SALARY NUMBER(6)
);

-- Table for Use Case 4: Referential Integrity (Parent)
CREATE TABLE DEMO.CUSTOMERS (
    CUSTOMER_ID NUMBER(10) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100)
);

-- Table for Use Case 4: Referential Integrity (Child)
CREATE TABLE DEMO.ORDERS (
    ORDER_ID NUMBER(10) PRIMARY KEY,
    ORDER_DATE DATE DEFAULT SYSDATE,
    CUSTOMER_ID NUMBER(10),
    TOTAL_AMOUNT NUMBER(10, 2),
    CONSTRAINT FK_ORDERS_CUSTOMERS
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES DEMO.CUSTOMERS(CUSTOMER_ID)
        DEFERRABLE INITIALLY DEFERRED
);

-- Table for complex types testing (moved to base setup)
CREATE TABLE DEMO.DATA_TYPES_TEST (
    ID NUMBER(10) PRIMARY KEY,
    TEXT_COL VARCHAR2(100),
    NUMBER_COL NUMBER(10,2),
    DATE_COL DATE,
    TIMESTAMP_COL TIMESTAMP,
    CLOB_COL CLOB,
    BLOB_COL BLOB,
    XML_COL XMLTYPE,
    LONG_COL LONG,
    RAW_COL RAW(50)
) XMLTYPE COLUMN XML_COL STORE AS CLOB;


-- Add new columns to create workaround for complex types
ALTER TABLE DEMO.DATA_TYPES_TEST ADD (XML_COL_CLOB CLOB);
ALTER TABLE DEMO.DATA_TYPES_TEST ADD (RAW_COL_VARCH VARCHAR2(100));

-- Create trigger to auto-convert XMLTYPE to CLOB and RAW to HEX for capture
CREATE OR REPLACE TRIGGER DEMO.trg_data_types_test
BEFORE INSERT OR UPDATE ON DEMO.DATA_TYPES_TEST
FOR EACH ROW
BEGIN
    -- XML conversion
    IF INSERTING OR UPDATING('XML_COL') THEN
        IF :NEW.XML_COL IS NOT NULL THEN
            :NEW.XML_COL_CLOB := :NEW.XML_COL.getClobVal();
        ELSE
            :NEW.XML_COL_CLOB := NULL;
        END IF;
    END IF;

    -- RAW conversion
    IF INSERTING OR UPDATING('RAW_COL') THEN
        IF :NEW.RAW_COL IS NOT NULL THEN
            :NEW.RAW_COL_VARCH := RAWTOHEX(:NEW.RAW_COL);
        ELSE
            :NEW.RAW_COL_VARCH := NULL;
        END IF;
    END IF;
END;
/
